sonar.projectKey=react-frontend

sonar.projectName=React Frontend

sonar.projectVersion=1.0

sonar.sources=src

sonar.tests=src

sonar.test.inclusions=**/*.test.tsx,**/*.test.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,dist/**,coverage/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=squ_a0f70a7ba0cfa3b97bffd6b51393c529362fa142